### ISSUE TITLE
AttributeError: 'module' object has no attribute 'prototype_search_with_coverage_state'

### ISSUE THREAD

**Issue by wubin1836** [tuzhaopeng/NMT-Coverage#1]
你好：

我在使用的时候出现了“AttributeError: 'module' object has no attribute 'prototype_search_with_coverage_state'” 这个问题？

请教一下，这是什么原因呢。

![image](https://cloud.githubusercontent.com/assets/22363994/23980150/fd965ee6-0a38-11e7-8e60-bd0cdbd98f1a.png)

**Comment by wubin1836** [comment]
![Uploading 屏幕快照 2017-03-16 上午11.08.40.png…]()

**Comment by tuzhaopeng** [comment]
"prototype_search_with_coverage_state" 是experiments/nmt/state.py中的定义的一个prototype（可以认为是一个dict），在运行该代码之前，你首先需要安装整个包，这样程序才能找到对应位置的state.py：

> To install NMT-Coverage in a multi-user setting
> 
> python setup.py develop --user
> 
> For general installation, simply use
> 
> python setup.py develop
> 
> NOTE: This will install the development version of Theano, if Theano is not currently installed.

**Comment by wubin1836** [comment]
非常感谢

这么快的恢复我

：）

**Comment by wubin1836** [comment]
非常感谢，这么快的回复我：）
