### ISSUE TITLE
文本生成模型，避免生成结果大多为训练数据里占比大的，有哪些方法？

### ISSUE THREAD

**Issue by guotong1988** [tuzhaopeng/NMT-Coverage#4]
请问下大神
@tuzhaopeng  多谢多谢

**Comment by tuzhaopeng** [comment]
这种情况在翻译里不常见，所以我对该问题也没有特别清晰的认识。

常见的方法是对数据进行处理，比如1）对占比小的样例进行over-sampling，使得两者的比例相当；2）加noisy，或者进行data
dropout，可以让占比大的数据每个iteration对模型都不是完全相同的，这也可以防止过拟合。

--
Zhaopeng Tu

Principal Researcher
Tencent AI Lab

http://www.zptu.net/
